### ISSUE TITLE
ESLint currently runs against the bundle

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/research-and-demos#37]
We'll want to exclude this file from linting:
`research-and-demos/minimal_redux_poc/__tests__/integration/react-example/test-react.build.js`

**Comment by mejackreed** [comment]
We have the eslintignore file which is being respected: https://github.com/ProjectMirador/research-and-demos/blob/master/minimal_redux_poc/.eslintignore

**Comment by sdellis** [comment]
This was due to my repo being in a bad git state. Running `git clean` fixed it.
